FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

ARG API_URL=http://localhost:8080
RUN sed -i "s|https://localhost:7096|${API_URL}|g" src/environments/environment.production.ts \
 && sed -i "s|https://localhost:7096|${API_URL}|g" src/environments/environment.ts

RUN npm run build -- --configuration=production

FROM nginx:1.27-alpine AS final
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/hospital-web/browser /usr/share/nginx/html
EXPOSE 80
