// <auto-generated />
using System;
using Hospital.VitalSigns.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hospital.VitalSigns.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VitalSignsDbContext))]
    [Migration("20260824201337_InitialVitalSigns")]
    partial class InitialVitalSigns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hospital.VitalSigns.Domain.VitalSigns.VitalSign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("DiastolicBloodPressure")
                        .HasColumnType("integer")
                        .HasColumnName("diastolic_blood_pressure");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("integer")
                        .HasColumnName("heart_rate");

                    b.Property<DateTimeOffset>("MeasuredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at_utc");

                    b.Property<decimal?>("OxygenSaturation")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("oxygen_saturation");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<int?>("RespiratoryRate")
                        .HasColumnType("integer")
                        .HasColumnName("respiratory_rate");

                    b.Property<int?>("SystolicBloodPressure")
                        .HasColumnType("integer")
                        .HasColumnName("systolic_blood_pressure");

                    b.Property<decimal?>("Temperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature");

                    b.HasKey("Id");

                    b.HasIndex("MeasuredAtUtc")
                        .HasDatabaseName("ix_vital_signs_measured_at_utc");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_vital_signs_patient_id");

                    b.ToTable("vital_signs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
