// <auto-generated />
using System;
using Hospital.Prescriptions.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hospital.Prescriptions.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PrescriptionsDbContext))]
    partial class PrescriptionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hospital.Prescriptions.Domain.Prescriptions.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset>("PrescribedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prescribed_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_prescriptions_patient_id");

                    b.HasIndex("PrescribedAtUtc")
                        .HasDatabaseName("ix_prescriptions_prescribed_at_utc");

                    b.ToTable("prescriptions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
